name: rubiks-solver
channels:
  - defaults
dependencies:
  - matplotlib=3.0.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.24.2
  - pip=19.2.3
  - python=3.7.1
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - pip:
    - opencv-python==4.1.1.26
